var url = "http://www.i-gomall.com";
var SiteUrl = url+"/shop";
var ApiUrl = url+"/wap/mo_bile";
var ApiUrl1 = url+"/wap";
var pagesize = 10;
var WapSiteUrl = url+"/wap";
var WapSiteUrl1 = url;
var IOSSiteUrl = "https://itunes.apple.com/us/app/shopnc-b2b2c/id879996267?l=zh&ls=1&mt=8";
var AndroidSiteUrl = "http://www.shopnc.net/download/app/AndroidShopNCMoblie.apk";
